# Generated by Django 2.0.5 on 2018-06-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_id', models.CharField(max_length=256, unique=True)),
                ('Title', models.CharField(max_length=256)),
                ('Credit', models.FloatField()),
                ('Semester', models.CharField(choices=[('1st Year Odd Semester', '1st Year Odd Semester'), ('1st Year Even Semester', '1st Year Even Semester'), ('2nd Year Odd Semester', '2nd Year Odd Semester'), ('2nd Year Even Semester', '2nd Year Even Semester'), ('3rd Year Odd Semester', '3rd Year Odd Semester'), ('3rd Year Even Semester', '3rd Year Even Semester'), ('4th Year Odd Semester', '4th Year Odd Semester'), ('4th Year Even Semester', '4th Year Even Semester')], default='1st Year Odd Semester', max_length=256)),
                ('Department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('MTE', 'MTE'), ('GCE', 'GCE'), ('ECE', 'ECE'), ('ETE', 'ETE'), ('ARCH', 'ARCH'), ('URP', 'URP'), ('BECM', 'BECM'), ('MSE', 'MSE'), ('IPE', 'IPE'), ('CFPE', 'CFPE')], default='CSE', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(choices=[('1st Year Odd Semester', '1st Year Odd Semester'), ('1st Year Even Semester', '1st Year Even Semester'), ('2nd Year Odd Semester', '2nd Year Odd Semester'), ('2nd Year Even Semester', '2nd Year Even Semester'), ('3rd Year Odd Semester', '3rd Year Odd Semester'), ('3rd Year Even Semester', '3rd Year Even Semester'), ('4th Year Odd Semester', '4th Year Odd Semester'), ('4th Year Even Semester', '4th Year Even Semester')], default='1st Year Odd Semester', max_length=256)),
                ('Department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('MTE', 'MTE'), ('GCE', 'GCE'), ('ECE', 'ECE'), ('ETE', 'ETE'), ('ARCH', 'ARCH'), ('URP', 'URP'), ('BECM', 'BECM'), ('MSE', 'MSE'), ('IPE', 'IPE'), ('CFPE', 'CFPE')], default='CSE', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Open',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st Year Odd Semester', '1st Year Odd Semester'), ('1st Year Even Semester', '1st Year Even Semester'), ('2nd Year Odd Semester', '2nd Year Odd Semester'), ('2nd Year Even Semester', '2nd Year Even Semester'), ('3rd Year Odd Semester', '3rd Year Odd Semester'), ('3rd Year Even Semester', '3rd Year Even Semester'), ('4th Year Odd Semester', '4th Year Odd Semester'), ('4th Year Even Semester', '4th Year Even Semester')], default='1st Year Odd Semester', max_length=256)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(choices=[('1st Year Odd Semester', '1st Year Odd Semester'), ('1st Year Even Semester', '1st Year Even Semester'), ('2nd Year Odd Semester', '2nd Year Odd Semester'), ('2nd Year Even Semester', '2nd Year Even Semester'), ('3rd Year Odd Semester', '3rd Year Odd Semester'), ('3rd Year Even Semester', '3rd Year Even Semester'), ('4th Year Odd Semester', '4th Year Odd Semester'), ('4th Year Even Semester', '4th Year Even Semester')], default='1st Year Odd Semester', max_length=256)),
                ('Department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('MTE', 'MTE'), ('GCE', 'GCE'), ('ECE', 'ECE'), ('ETE', 'ETE'), ('ARCH', 'ARCH'), ('URP', 'URP'), ('BECM', 'BECM'), ('MSE', 'MSE'), ('IPE', 'IPE'), ('CFPE', 'CFPE')], default='CSE', max_length=256)),
                ('Name', models.CharField(max_length=256)),
                ('Roll', models.CharField(max_length=7)),
                ('Credit', models.FloatField()),
                ('Backlogs', models.TextField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Remind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateField()),
            ],
        ),
    ]
