# Generated by Django 2.0.5 on 2018-06-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_onlysemester'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Courses',
            field=models.CharField(default='Some String', max_length=512),
        ),
    ]
