# Generated by Django 2.0.5 on 2018-06-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_registration_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Type',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Optional', 'Optional')], default='Compulsory', max_length=256),
        ),
    ]
