# Generated by Django 2.0.5 on 2018-06-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_registration_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Type',
        ),
    ]
