# Generated by Django 2.0.5 on 2018-06-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_optionalcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Course_id',
            field=models.CharField(max_length=256),
        ),
    ]
